local MSG_SET_PROPS = hash( "setProps" )


function on_message( self, message_id, message, sender )
	if message_id == MSG_SET_PROPS then
		local amount = tonumber( message.rewardsubtype )
		-- beware: standard reward.script sets amount to "1" after 1 sec
		-- make sure that for coins, the defined amount is the last to be set
		timer.delay( 1.5, false, function() 
			go.set( "#script", "amount", amount )
		end )
	end
end

